core/urls.py
from django.urls import path


from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<str:id>/', add_to_cart, name='add-to-cart'),
    path('addtocart', addtocart, name='addtocart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<str:id>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<str:id>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('livraregratuita/', LivrareGratuita.as_view(), name='livraregratuita'),
    path('despre_noi/', DESPRE_NOI.as_view(), name='despre_noi'),
    path('contacteaza_ne/', CONTACTEAZA_NE.as_view(), name='contacteaza_ne'),
    path('cum_comand/', CUM_COMAND.as_view(), name='cum_comand'),
    path('ghid_de_marimi/', GHID_DE_MARIMI.as_view(), name='ghid_de_marimi'),
    path('newsletter/', NEWSLETTER.as_view(), name='newsletter'),
    path('politica_de_confidentialitate/', POLITICA_DE_CONFIDENTIALITATE.as_view(), name='politica_de_confidentialitate'),
    path('politica_de_retur/', POLITICA_DE_RETUR.as_view(), name='politica_de_retur'),
    path('termenii_si_conditiile/', TERMENII_SI_CONDITIILE.as_view(), name='termenii_si_conditiile'),
    path('product_info/<slug>/', CategoryView2.as_view(), name='category2'),
    path('send_email', send_email, name='send_email'),

    path('Received',PaymentReceivedTemplate, name='PaymentReceived'),
    path('addCoupon',addCoupon, name='addCoupon'),
    path('myaccount',myaccount, name='myaccount'),
    path('myorders',myorders, name='myorders'),
    path('refundorder',refundorder, name='refundorder'),
    path('addsubcriber',addsubcriber, name='addsubcriber'),
    path('adminUser',adminUser, name='adminUser'),
    path('getOrders',getOrders, name='getOrders'),
    path('filterItems',filterItems, name='filterItems'),
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import  i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
urlpatterns =[
    path('i18n/', include('django.conf.urls.i18n'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




urlpatterns += i18n_patterns(
    path(r'admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/Category_temp2.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="/" class="s-text16">
			{% trans "Home" %}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="{% url 'core:category' object.category.slug %}" class="s-text16">
			{{ object.category }}
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{object.title}}
		</span>
	</div>

	<!-- Product Detail -->
	<div class="container bgwhite p-t-35 p-b-80">
		<div class="flex-w flex-sb">
			<div class="w-size13 p-t-30 respon5">
				<div class="wrap-slick3 flex-sb flex-w">
					<div class="wrap-slick3-dots"></div>

					<div class="slick3">
						<div class="item-slick3" data-thumb="{{ object.image.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image.url }}" alt="{{ object.title }}">
							</div>
						</div>

						<div class="item-slick3" data-thumb="{{ object.image2.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image2.url }}" alt="IMG-PRODUCT">
							</div>

						</div>
						{% if object.image3.url %}
						<div class="item-slick3" data-thumb="{{ object.image3.url }}">
							<div class="wrap-pic-w">
								<img src="{{ object.image3.url }}" alt="IMG-PRODUCT">
							</div>
						</div>
						{% endif %}
					</div>
				</div>
			</div>

			<div class="w-size14 p-t-30 respon5">
				<h4 class="product-detail-name m-text16 p-b-13">
					{{object.title}}
				</h4>

				
				{% if object.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="font-size: 1.5rem;">
									{{ object.price }} RON
								</span>

								<span class="block2-newprice m-text8 p-r-5" style="font-size: 1.5rem;">
									{{ object.discount_price }} RON
								</span>
								{% else %}
								<span class="m-text17">
									{{object.price}} RON
								</span>
								{% endif %}

				<p class="s-text8 p-t-10">
					{{ object.description_short }}
				</p>

				<!--  -->
				<div class="p-t-33 p-b-60 ">
					<div class="flex-m flex-w p-b-10">
						<div class="s-text15 w-size15 t-center">
							{% trans "Size" %} 
						</div>

						<div class="rs2-select2 rs3-select2 w-size16">
							<select class="form-control" name="size" id="size">
								<option>{% trans "Choose the size" %} </option>
								<option>S</option>
								<option>M</option>
								<option>L</option>
								<option>XL</option>
							</select>
						</div>
						
					</div>
					
					

					
					
					
		</div>
					

					<div class="container-fluid"><div class="progress">
					<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40"
					aria-valuemin="0" aria-valuemax="100" style="width:{{item.remainingPercents}}%;background:orange">
						{{object.remainingPercents}}%
					</div>
					</div>
					<div class="flex-r-m flex-w ">
						<div class="p-b-45">
					<span class="s-text8 m-r-35">{% trans "cantity" %}: {{ object.rQty }}</span>
					
				</div>
				
						<div class="w-size16 flex-m flex-w">
							
							<div class="flex-w bo5 of-hidden ">
								
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="m-text18 t-center num-product" type="number" readonly name="num-product" id="qty" min="1" value="1" >

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>
							
							<br>
							<br>
							<br>

							{% if item.rQty > 0 %}
									<button onclick="addToCart({{object.id}})" class="btn btn-primary form-control" style="margin: 2px;">Add To Cart</button>
											</button>
									{% else %}
									<button onclick="addToCart({{object.id}})" class="btn btn-danger form-control" style="margin: 2px;">
												{% trans "Item Out of Stock" %}
											</button>
									{% endif %}
									
							
						
						</div>
						
					</div>
				</div>
				
				

			
			
			</div>
		</div>
	</div>




	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<div id="dropDownSelect2"></div>
<script>
	function addToCart(id)
	{
		var size=document.getElementById("size").value;
		
		var qty=document.getElementById("qty").value;
		if(size=='{% trans "Choose the size" %}')
		{
			size="M"
		}
		
		data={"item_id":id,"size":size,"Q":qty}
		console.log(data)
		$.ajax(
    {
        type:"POST",
        url: "/en/addtocart",
		headers: {

			"X-CSRFToken": getCookie(),
		},
		data: JSON.stringify(data),

        
        success: function( data ) 
        {

			document.getElementById("lblCartCount").innerHTML=data["count"];
			 
				if (data["msg"]=="Error")
				{
						swal(data["item"], data["msg"], "error");
				}
				else{
					swal(data["item"], data["msg"], "success");
				}
				
				
			
            console.log(data);
        }
     })

	}
</script>
	{% endblock content %}

templates/GHID_DE_MARIMI_temp.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<h1>
    GHID_DE_MARIMI view add your text here
</h1>
{% endblock content %}

templates/LivrareGratuita_temp.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<h1>
    LivrareGratuita view add your text here!
</h1>
{% endblock content %}

templates/NEWSLETTER_temp.html
{% extends 'base.html' %} 
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<h1>
    NEWSLETTER view add your text here!
</h1>
{% endblock content %}

templates/POLITICA_DE_RETUR_temp.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

<h1>
    POLITICA_DE_RETUR view add your text here!
</h1>
{% endblock content %}

templates/nav.html
{% load static %}
{% load i18n %}

{% load cart_template_tags %}
{% load category_template_tags %}
<style>
	.topbar {
		background-color: white;
		color: black !important;
	}

	.topbar a:hover {
		color: black;
	}

	.badge {
		padding-left: 9px;
		padding-right: 9px;
		-webkit-border-radius: 9px;
		-moz-border-radius: 9px;
		border-radius: 9px;
		background-color: white;
	}

	.label-warning[href],
	.badge-warning[href] {
		background-color: #c67605;
	}

	#lblCartCount {
		font-size: 12px;
		background: black;
		color: #fff;
		padding: 0 5px;
		vertical-align: top;
		margin-left: -10px;
	}
</style>

<!-- Header -->
<header class="header1 container-fluid">
	<!-- Header desktop -->
	<div class="container-menu-header">
		<div class="topbar">
			<div class="topbar-social">
				<a href="https://www.facebook.com/nexusgamingro/" class="topbar-social-item fab fa-facebook"></a>
				<a href="https://instagram.com/nexusgamingro?igshid=YmMyMTA2M2Y="
					class="topbar-social-item fab fa-instagram"></a>
				<a href="https://youtube.com/channel/UClxQeD_l3A-jth_PdjyEUwA"
					class="topbar-social-item fab fa-youtube"></a>

				<form id="langForm" action="{% url 'set_language' %}" method="post">
					{% csrf_token %}

					{% get_current_language as LANGUAGE_CODE %}
					<input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
					{% if LANGUAGE_CODE == 'ro' %}
					<button type="submit" class="codrops-icon" name="language" value="en">

						Romanian</button>
					{% else %}
					<button type="submit" class="codrops-icon" name="language" value="ro">
						English
					</button>
					{% endif %}
				</form>



			</div>

			<span class="topbar-child1">
				{% trans "Free delivery for orders that exceed" %} &#108;&#101;&#105;100
			</span>

			<div class="topbar-child2">
				<span class="topbar-email">
					<a href="">

					</a>
				</span>

			</div>
		</div>

		<div class="wrap_header">
			<!-- Logo -->
			<a href="/" class="logo">
				<p style="color: black; "><img src="{% static 'images/nexusmedia_new_logo.png' %}"></p>
			</a>

			<!-- Menu -->
			<div class="wrap_menu sidebar">
				<nav class="menu">
					<ul class="main_menu">
						{% if request.user.is_authenticated and request.user.is_superuser %}
						<li>
							<a href="/adminUser">{% trans "admin" %}</a>

						</li>
						{% endif %}
						<li>
							<a href="/">{% trans "Home" %}</a>

						</li>
						

						<li>
							<a href="/shop/">{% trans "All Products" %}</a>
						</li>

						{% categories %}

						{% if request.user.is_authenticated %}

						<li>
							<a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
						</li>
						{% else %}
						<li>
							<a href="#">{% trans "Login" %}</a>
							<ul class="sub_menu">
								<li><a href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
								<li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
							</ul>
						</li>
						{% endif %}
					</ul>
				</nav>
			</div>

			<!-- Header Icon -->
			<div class="header-icons">
				<div class="nav-item dropdown">

					<a href="#" class="nav-link dropdown-toggle" class="header-wrapicon1 dis-block" id="navbarDropdown"
						role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="/myaccount">My Account</a>
						<a class="dropdown-item" href="/myorders">Orders</a>
						<a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>


					</div>
				</div>


				<span class="linedivide1"></span>
				{% if request.user.is_authenticated %}
				<li>
					<a href="{% url 'core:order-summary' %}">
						<img src="{% static 'images/icons/icon-header-02.png' %} " alt="">


						<span class="badge badge-dark" id='lblCartCount'>{{ request.user|cart_item_count }}</span>
					</a>
				</li>

				{% endif %}

			</div>
			<!-- Header Mobile -->
			<div class="wrap_header_mobile">
				<!-- Logo moblie -->
				<a href="index.html" class="logo-mobile">
					<img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO">
				</a>

				<!-- Button show menu -->
				<div class="btn-show-menu">
					<!-- Header Icon mobile -->
					<div class="header-icons-mobile">
						<a href="#" class="header-wrapicon1 dis-block">
							<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
						</a>

						<span class="linedivide2"></span>

						<div class="header-wrapicon2">
							<img src="{% static 'images/icons/icon-header-02.png' %}"
								class="header-icon1 js-show-header-dropdown" alt="ICON">
							<span class="header-icons-noti">0</span>

							<!-- Header cart noti -->
							<div class="header-cart header-dropdown">
								<ul class="header-cart-wrapitem">
									<li class="header-cart-item">
										<div class="header-cart-item-img">
											<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
										</div>

										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												{% trans "White Shirt With Pleat Detail Back" %}
											</a>

											<span class="header-cart-item-info">
												1 x &#108;&#101;&#105;19.00
											</span>
										</div>
									</li>

									<li class="header-cart-item">
										<div class="header-cart-item-img">
											<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
										</div>

										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												{% trans "Converse All Star Hi Black Canvas" %}
											</a>

											<span class="header-cart-item-info">
												1 x &#108;&#101;&#105;39.00
											</span>
										</div>
									</li>

									<li class="header-cart-item">
										<div class="header-cart-item-img">
											<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
										</div>

										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												{% trans "Nixon Porter Leather Watch In Tan" %}
											</a>

											<span class="header-cart-item-info">
												1 x &#108;&#101;&#105;17.00
											</span>
										</div>
									</li>
								</ul>

								<div class="header-cart-total">
									{% trans "Total" %}: RON
								</div>

								<div class="header-cart-buttons">
									<div class="header-cart-wrapbtn">
										<!-- Button -->
										<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
											{% trans "View Cart" %}
										</a>
									</div>

									<div class="header-cart-wrapbtn">
										<!-- Button -->
										<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
											{% trans "Check Out" %}
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</div>
				</div>
			</div>

			<!-- Menu Mobile -->
			<div class="wrap-side-menu">
				<nav class="side-menu">
					<ul class="main-menu">
						<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
							<span class="topbar-child1">
								{% trans "Free shipping for standard order over" %}
							</span>
						</li>

						<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
							<div class="topbar-child2-mobile">
								<span class="topbar-email">

								</span>

							</div>
						</li>

						<li class="item-topbar-mobile p-l-10">
							<div class="topbar-social-mobile">
								<a href="#" class="topbar-social-item fa fa-facebook"></a>
								<a href="#" class="topbar-social-item fa fa-instagram"></a>
								<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
								<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
								<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
							</div>
						</li>


						<li class=" ">
							<a href="/">{% trans "Home" %}</a>
						</li>

						<li class=" ">
							<a href="/shop">{% trans "Shop" %}</a>
						</li>

						{% categories_mobile %}

						{% if request.user.is_authenticated %}
						<li class=" ">
							<a href="{% url 'core:order-summary' %}">{% trans "Cart" %}<span
									class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
						</li>
						<li class=" ">
							<a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
						</li>
						{% else %}
						<li class=" ">
							<a href="#">{% trans "Login" %}</a>
							<ul class="sub-menu">
								<li><a href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
								<li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
							</ul>
							<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
						</li>
						{% endif %}

					</ul>
				</nav>
			</div>

</header>
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="mobiletopbar">
	
		{% if request.user.is_authenticated %}
			
			<li class="navbar-brand">
				Nexus Shop
				<a href="{% url 'core:order-summary' %}" class="nav-link">{% trans "Cart" %}<span
						class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
			</li>
			
			{% else %}
			<li class="navbar-brand">

				Nexus Shop
			</li>
		{% endif %}
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
		aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			
			<li class="nav-item item-topbar-mobile p-l-20 p-t-8 p-b-8">
				<span class="topbar-child1 nav-link">
					{% trans "Free shipping for standard order over" %}
				</span>
			</li>

			<li class="nav-item  item-topbar-mobile p-l-20 p-t-8 p-b-8">
				<div class="topbar-child2-mobile nav-link">
					<span class="topbar-email">

					</span>

				</div>
			</li>

			<li class="nav-item item-topbar-mobile p-l-10">
				<div class="topbar-social-mobile nav-link">
					<a href="#" class="topbar-social-item fa fa-facebook"></a>
					<a href="#" class="topbar-social-item fa fa-instagram"></a>
					<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
					<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
					<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
				</div>
			</li>

			
			{% if request.user.is_authenticated and request.user.is_superuser %}
				<li class="  nav-item ">
				<a class="nav-link"  href="/adminUser">{% trans "Admin" %}</a>
			</li>
			{% endif %}
				
			
			<li class="  nav-item ">
				<a class="nav-link"  href="/">{% trans "Home" %}</a>
			</li>
			<li class="  nav-item">
				<a class="nav-link" href="/shop">{% trans "Shop" %}</a>
			</li>
			<li class="nav-item">
					{% categories_mobile %}
			</li>
			

			{% if request.user.is_authenticated %}
			<li class="  nav-item">
				<a href="{% url 'core:order-summary' %}" class="nav-link">{% trans "Cart" %}<span
						class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
			</li>
			<li class="  nav-item">
				<a href="{% url 'account_logout' %}" class="nav-link">{% trans "Logout" %}</a>
			</li>
			{% else %}
			<li class="nav-item">
				
					<li><a class="nav-link" href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
					<li><a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
				
				
			</li>
			{% endif %}


		</ul>
	</div>
</nav>
<script>

	$(window).on('resize', function(){
		
		
    var win = $(this);

    console.log(win.width(), win.height());
    if (win.width() >= 980) {
			$("#mobiletopbar").css("display","none")
			$("#setfooterformobile").css("margin-left","40%")
	 }
	 else{
		$("#mobiletopbar").css("display","block")
		$("#setfooterformobile").css("margin-left","-10%")
	 }
});
	
	

</script>

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "Your Cart" %}</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">{% trans "Picture" %}</th>
            <th scope="col">{% trans "Product Name" %}</th>
        
            <th scope="col">{% trans "Size" %}</th>
            <th scope="col">{% trans "Price" %}</th>
            <th scope="col">{% trans "Amount" %}</th>
            <th scope="col">{% trans "Total Price" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            
            <td>{{ order_item.size }}</td>
            
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.id %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.id %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %} RON
               {{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary" style="color:black">  {% trans "Saving" %}  {{ order_item.get_amount_saved }} RON</span>
              {% else %}
               {{ order_item.get_total_item_price}} RON
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.id %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">{% trans "Your cart is empty" %}</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>{% trans "Coupon" %} : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
         <tr>
        	<td colspan="5"><b>{% trans "Sub Total" %} : </b></td>
        	<td><b>{{ object.get_total }} RON </b></td>
        </tr>
        <tr>
        	<td colspan="5"><b>{% trans "Shipping Fee" %} : </b></td>
        	<td><b>{{ object.Shippingfee }} RON</b></td>
        </tr>
        
        <tr>
        	<td colspan="5"><b>{% trans "Total price" %} : </b></td>
        	<td><b>{{ object.grandTotal }} RON</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">{% trans "Checkout" %}</a>
        		<a href="/" class="btn btn-primary float-right">{% trans "Continue Shopping" %}</a>

        	</td>
        </tr>
       
      </table>
    </div>
  </div>
</div>

{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}

{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>{% trans "Request Refund" %}</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}

templates/send_email.html
Nexus shop

Message received from {{data.email}}

Name:{{data.name}}
Subject:{{data.subject}}
Message:{{data.message}}